# المرحلة الأولى: بناء المشروع
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# نسخ ملف المشروع واسترجاع الـ dependencies
COPY *.csproj ./
RUN dotnet restore

# نسخ باقي الملفات وبناء المشروع
COPY . ./
RUN dotnet publish -c Release -o /app

# المرحلة الثانية: تشغيل المشروع
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app .
ENV ASPNETCORE_URLS=http://0.0.0.0:${PORT}
EXPOSE 8080
ENTRYPOINT ["dotnet", "Docsera.dll"]
